// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARjk9OWPOImi0cXvK6hzY06hTlVfKZ_No',
    appId: '1:598684071371:web:855d0bd6b4113b856bb24e',
    messagingSenderId: '598684071371',
    projectId: 'mdpgoldbelajar',
    authDomain: 'mdpgoldbelajar.firebaseapp.com',
    databaseURL: 'https://mdpgoldbelajar-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgoldbelajar.firebasestorage.app',
    measurementId: 'G-TXXC0M35C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0EjvuriKd_h0Ktc55XlbUBVOYAq1LDPA',
    appId: '1:598684071371:android:750a799241492f4e6bb24e',
    messagingSenderId: '598684071371',
    projectId: 'mdpgoldbelajar',
    databaseURL: 'https://mdpgoldbelajar-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgoldbelajar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo2vamSZEbPlhoNGY6344UE65oILHR8t4',
    appId: '1:598684071371:ios:db7670a2914d1b586bb24e',
    messagingSenderId: '598684071371',
    projectId: 'mdpgoldbelajar',
    databaseURL: 'https://mdpgoldbelajar-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgoldbelajar.firebasestorage.app',
    iosBundleId: 'com.example.mdpGoldBelajar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo2vamSZEbPlhoNGY6344UE65oILHR8t4',
    appId: '1:598684071371:ios:db7670a2914d1b586bb24e',
    messagingSenderId: '598684071371',
    projectId: 'mdpgoldbelajar',
    databaseURL: 'https://mdpgoldbelajar-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgoldbelajar.firebasestorage.app',
    iosBundleId: 'com.example.mdpGoldBelajar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARjk9OWPOImi0cXvK6hzY06hTlVfKZ_No',
    appId: '1:598684071371:web:5303f3ca648a558c6bb24e',
    messagingSenderId: '598684071371',
    projectId: 'mdpgoldbelajar',
    authDomain: 'mdpgoldbelajar.firebaseapp.com',
    databaseURL: 'https://mdpgoldbelajar-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgoldbelajar.firebasestorage.app',
    measurementId: 'G-RXLD7446R0',
  );
}
