// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrYXqnoa1adc0GpjWxw7FP2GDo1QGAZzI',
    appId: '1:435742237842:web:1e4203e36a1756cf44b24b',
    messagingSenderId: '435742237842',
    projectId: 'game-29839',
    authDomain: 'game-29839.firebaseapp.com',
    databaseURL: 'https://game-29839-default-rtdb.firebaseio.com',
    storageBucket: 'game-29839.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZcrnQ0OwJpCAZHcp9zQ4nJ5gHA5lIMrs',
    appId: '1:435742237842:android:90ef7ced6f13fac144b24b',
    messagingSenderId: '435742237842',
    projectId: 'game-29839',
    databaseURL: 'https://game-29839-default-rtdb.firebaseio.com',
    storageBucket: 'game-29839.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFuW2BKrMblRcXA3_Fzddr1pQS2LQpbvY',
    appId: '1:435742237842:ios:ada032c9ab43ca8244b24b',
    messagingSenderId: '435742237842',
    projectId: 'game-29839',
    databaseURL: 'https://game-29839-default-rtdb.firebaseio.com',
    storageBucket: 'game-29839.firebasestorage.app',
    iosBundleId: 'com.example.game',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFuW2BKrMblRcXA3_Fzddr1pQS2LQpbvY',
    appId: '1:435742237842:ios:ada032c9ab43ca8244b24b',
    messagingSenderId: '435742237842',
    projectId: 'game-29839',
    databaseURL: 'https://game-29839-default-rtdb.firebaseio.com',
    storageBucket: 'game-29839.firebasestorage.app',
    iosBundleId: 'com.example.game',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrYXqnoa1adc0GpjWxw7FP2GDo1QGAZzI',
    appId: '1:435742237842:web:abe69d526a5e46d244b24b',
    messagingSenderId: '435742237842',
    projectId: 'game-29839',
    authDomain: 'game-29839.firebaseapp.com',
    databaseURL: 'https://game-29839-default-rtdb.firebaseio.com',
    storageBucket: 'game-29839.firebasestorage.app',
  );

}