// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWIQ1Cw0QRVCSxi07f1UxKD4XtDa4B11s',
    appId: '1:730415448473:web:db99e4f406f901b38e1308',
    messagingSenderId: '730415448473',
    projectId: 'daftarbelanja-b3135',
    authDomain: 'daftarbelanja-b3135.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-b3135-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-b3135.firebasestorage.app',
    measurementId: 'G-SQ1B50DE6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAokLvGkDdHZit0MMJI4fDs_UZQYg95tTo',
    appId: '1:730415448473:android:f352c1def82569428e1308',
    messagingSenderId: '730415448473',
    projectId: 'daftarbelanja-b3135',
    databaseURL: 'https://daftarbelanja-b3135-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-b3135.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvkD0D8q2LxS8mKeMMfB1Q5HeNCMA8w1Y',
    appId: '1:730415448473:ios:a61da5ec37eae7478e1308',
    messagingSenderId: '730415448473',
    projectId: 'daftarbelanja-b3135',
    databaseURL: 'https://daftarbelanja-b3135-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-b3135.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvkD0D8q2LxS8mKeMMfB1Q5HeNCMA8w1Y',
    appId: '1:730415448473:ios:a61da5ec37eae7478e1308',
    messagingSenderId: '730415448473',
    projectId: 'daftarbelanja-b3135',
    databaseURL: 'https://daftarbelanja-b3135-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-b3135.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWIQ1Cw0QRVCSxi07f1UxKD4XtDa4B11s',
    appId: '1:730415448473:web:05b52857919fcd8b8e1308',
    messagingSenderId: '730415448473',
    projectId: 'daftarbelanja-b3135',
    authDomain: 'daftarbelanja-b3135.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-b3135-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-b3135.firebasestorage.app',
    measurementId: 'G-P6FTCW89S8',
  );
}
