// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6r7tYjgUcavD24Kfb-ZPB6WLtxg3uMqY',
    appId: '1:485969055035:web:1261034ce533792391fb1e',
    messagingSenderId: '485969055035',
    projectId: 'mdpgold-bafbc',
    authDomain: 'mdpgold-bafbc.firebaseapp.com',
    databaseURL: 'https://mdpgold-bafbc-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-bafbc.firebasestorage.app',
    measurementId: 'G-0EB71QJ6D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Jdne6tz0Kp0xj8Hflim8LTw1FlYgMpE',
    appId: '1:485969055035:android:fcd89089b62b27ab91fb1e',
    messagingSenderId: '485969055035',
    projectId: 'mdpgold-bafbc',
    databaseURL: 'https://mdpgold-bafbc-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-bafbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHryl_TWhAIBb1KQDRFGG9ZNehydeJHWQ',
    appId: '1:485969055035:ios:d06129346842b91e91fb1e',
    messagingSenderId: '485969055035',
    projectId: 'mdpgold-bafbc',
    databaseURL: 'https://mdpgold-bafbc-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-bafbc.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHryl_TWhAIBb1KQDRFGG9ZNehydeJHWQ',
    appId: '1:485969055035:ios:d06129346842b91e91fb1e',
    messagingSenderId: '485969055035',
    projectId: 'mdpgold-bafbc',
    databaseURL: 'https://mdpgold-bafbc-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-bafbc.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6r7tYjgUcavD24Kfb-ZPB6WLtxg3uMqY',
    appId: '1:485969055035:web:05099acf126cb94291fb1e',
    messagingSenderId: '485969055035',
    projectId: 'mdpgold-bafbc',
    authDomain: 'mdpgold-bafbc.firebaseapp.com',
    databaseURL: 'https://mdpgold-bafbc-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-bafbc.firebasestorage.app',
    measurementId: 'G-9F5P8HF85E',
  );
}
